name: Deploy, Test, and Destroy Lambda Function

on:
  workflow_dispatch:

jobs:
  deploy_test_and_destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        working-directory: terraform-lambda
        run: terraform init

      - name: Terraform Apply
        working-directory: terraform-lambda
        run: terraform apply -auto-approve

      - name: Test Lambda Function
        working-directory: terraform-lambda
        run: |
          npm install # Install dependencies for testing
          npm test    # Run tests

      - name: Sleep Before Destroy
        run: sleep 10  # Wait for 10 seconds before proceeding with destroy

      - name: Terraform Destroy
        working-directory: terraform-lambda
        run: terraform destroy -auto-approve
