name: Upload to AWS S3

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get AWS Credentials
        id: aws-credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::338435713321:role/GithubActionsRole
          role-session-name: GitHubActions
          aws-region: us-east-1
          external-id: ${{ secrets.OIDC_EXTERNAL_ID }}

      - name: Upload to S3
        run: |
          aws s3 sync ./upload s3://awsrdh --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ steps.aws-credentials.outputs.access_key_id }}
          AWS_SECRET_ACCESS_KEY: ${{ steps.aws-credentials.outputs.secret_access_key }}
          AWS_SESSION_TOKEN: ${{ steps.aws-credentials.outputs.session_token }}
