######################### Acess  Using User credentials and sync action to upload files to S3 ###############################

# name: Upload to S3 using User credentials
# on:
#   push:
#     branches:
#       - main
# jobs:
#   upload:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Upload to S3
#         uses: jakejarvis/s3-sync-action@master
#         with:
#           args: --follow-symlinks --delete
#         env:
#           AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
#           AWS_REGION: ${{ secrets.AWS_REGION }}
#           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           SOURCE_DIR: ./upload

######################### Acess  Using User credentials and simple command to upload files to S3 ###############################

# name: Upload to S3
# on:
#   push:
#     branches:
#       - main
# permissions:
#   id-token: write
#   contents: read
# jobs:
#   upload:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2
#       - name: Upload to S3
#         run: |
#           aws s3 sync ./upload s3://rdhbucket12 --delete
#         env:
#           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

############################ Acess  Using OIDC to upload files to S3 ##########################

name: Upload to S3
on:
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: read
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: 'us-east-1'
          role-to-assume: ${{ secrets.WRITE_ROLE }}
          role-session-name: OIDCSession
      - name: Upload to S3
        run: |
          aws s3 sync ./upload s3://rdhbucket12 --delete
